"""Added expense and salary expense tables

Revision ID: 02cad5913f1b
Revises: 5abf1205e6e3
Create Date: 2025-06-18 17:57:48.980633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02cad5913f1b'
down_revision: Union[str, None] = '5abf1205e6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_expenses_id'), 'basic_expenses', ['id'], unique=False)
    op.create_table('salary_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('salary_amount', sa.Float(), nullable=False),
    sa.Column('salary_month', sa.String(), nullable=False),
    sa.Column('salary_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_expenses_id'), 'salary_expenses', ['id'], unique=False)
    op.alter_column('regular_students', 'marital_status',
               existing_type=postgresql.ENUM('single', 'married', 'widowed', 'divorced', name='maritalstatusenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regular_students', 'marital_status',
               existing_type=postgresql.ENUM('single', 'married', 'widowed', 'divorced', name='maritalstatusenum'),
               nullable=True)
    op.drop_index(op.f('ix_salary_expenses_id'), table_name='salary_expenses')
    op.drop_table('salary_expenses')
    op.drop_index(op.f('ix_basic_expenses_id'), table_name='basic_expenses')
    op.drop_table('basic_expenses')
    # ### end Alembic commands ###
