"""Added user name in user table

Revision ID: 120d011e9c93
Revises: 082cdea650db
Create Date: 2025-06-20 16:20:10.498091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120d011e9c93'
down_revision: Union[str, None] = '082cdea650db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('select_date', sa.Date(), nullable=False))
    op.drop_column('transactions', 'admission_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('admission_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'select_date')
    # ### end Alembic commands ###
