"""Added user name in user table

Revision ID: 203369e3edff
Revises: 9f3d0b18b84c
Create Date: 2025-06-20 17:40:07.057113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203369e3edff'
down_revision: Union[str, None] = '9f3d0b18b84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('basic_expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('salary_expenses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('salary_expenses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_expenses', 'updated_at')
    op.drop_column('salary_expenses', 'created_at')
    op.drop_column('basic_expenses', 'updated_at')
    op.drop_column('basic_expenses', 'created_at')
    # ### end Alembic commands ###
