"""Add RoleEnum to user

Revision ID: 3323f7488820
Revises: 6bcaba5c2f7c
Create Date: 2025-07-02 15:19:10.549060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3323f7488820'
down_revision: Union[str, None] = '6bcaba5c2f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('profiles', 'business_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'primary_contact_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'pincode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profiles', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('profiles', 'primary_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('primary_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('profiles', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'pincode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'primary_contact_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profiles', 'business_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
