"""add pending_amount, payment_method, created_at to transactions

Revision ID: 3685ced3e10f
Revises: f8c2d8de4020
Create Date: 2025-06-24 15:00:03.118008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3685ced3e10f'
down_revision: Union[str, None] = 'f8c2d8de4020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns with default values
    op.add_column('transactions', sa.Column(
        'pending_amount',
        sa.Float(),
        server_default='0.0',
        nullable=False
    ))
    op.add_column('transactions', sa.Column(
        'payment_method',
        sa.String(),
        server_default="'cash'",
        nullable=False
    ))
    op.add_column('transactions', sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=True
    ))

    # ✅ Set default dates for existing NULLs
    op.execute("UPDATE transactions SET payment_month_start = CURRENT_DATE WHERE payment_month_start IS NULL;")
    op.execute("UPDATE transactions SET payment_month_end = CURRENT_DATE WHERE payment_month_end IS NULL;")

    # Now alter columns to be non-nullable
    op.alter_column('transactions', 'payment_month_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transactions', 'payment_month_end',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'payment_month_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transactions', 'payment_month_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('transactions', 'created_at')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'pending_amount')
    # ### end Alembic commands ###
