"""Added user name in user table

Revision ID: 805d029eaa5f
Revises: d364dd26dd7b
Create Date: 2025-06-20 16:31:32.684977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805d029eaa5f'
down_revision: Union[str, None] = 'd364dd26dd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_date', sa.Date(), nullable=False))
    op.drop_column('transactions', 'select_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('select_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'payment_date')
    # ### end Alembic commands ###
