"""Added batch course and duration changes

Revision ID: c5a5494f3d3e
Revises: 9de4fe56f125
Create Date: 2025-06-19 11:15:29.171016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a5494f3d3e'
down_revision: Union[str, None] = '9de4fe56f125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('courses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment_durations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('payment_durations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_durations', 'updated_at')
    op.drop_column('payment_durations', 'created_at')
    op.drop_column('courses', 'updated_at')
    op.drop_column('courses', 'created_at')
    # ### end Alembic commands ###
