"""create pte_students table

Revision ID: d97478a828e9
Revises: 21d5b009fbf7
Create Date: 2025-06-18 10:35:38.996581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97478a828e9'
down_revision: Union[str, None] = '21d5b009fbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regular_students', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('regular_students', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regular_students', 'updated_at')
    op.drop_column('regular_students', 'created_at')
    # ### end Alembic commands ###
