"""Added user name in user table

Revision ID: ee22b955bbd0
Revises: ead1b22960f7
Create Date: 2025-06-20 11:59:52.851671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee22b955bbd0'
down_revision: Union[str, None] = 'ead1b22960f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('business_name', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('primary_contact_number', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('secondary_contact_number', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('primary_email', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('secondary_email', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('pincode', sa.String(), nullable=False))
    op.add_column('profiles', sa.Column('gst_number', sa.String(), nullable=True))
    op.drop_column('profiles', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'gst_number')
    op.drop_column('profiles', 'pincode')
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'secondary_email')
    op.drop_column('profiles', 'primary_email')
    op.drop_column('profiles', 'secondary_contact_number')
    op.drop_column('profiles', 'primary_contact_number')
    op.drop_column('profiles', 'business_name')
    # ### end Alembic commands ###
