"""Add payment_month_start and end

Revision ID: f8c2d8de4020
Revises: 203369e3edff
Create Date: 2025-06-24 14:46:29.807774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8c2d8de4020'
down_revision: Union[str, None] = '203369e3edff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teacher_attendance_association_attendance_id_fkey'), 'teacher_attendance_association', type_='foreignkey')
    op.drop_constraint(op.f('teacher_attendance_association_teacher_id_fkey'), 'teacher_attendance_association', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_attendance_association', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_attendance_association', 'teacher_attendances', ['attendance_id'], ['id'], ondelete='CASCADE')
    op.add_column('transactions', sa.Column('payment_month_start', sa.Date(), nullable=True))
    op.add_column('transactions', sa.Column('payment_month_end', sa.Date(), nullable=True))

    op.alter_column('transactions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'amount_paid',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('transactions_student_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'regular_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transactions', 'payment_month')
    op.drop_column('transactions', 'pending_amount')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('payment_method', postgresql.ENUM('card', 'cash', 'upi', name='paymentmethodenum'), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('pending_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('payment_month', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_student_id_fkey'), 'transactions', 'regular_students', ['student_id'], ['id'])
    op.alter_column('transactions', 'amount_paid',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('transactions', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'payment_month_end')
    op.drop_column('transactions', 'payment_month_start')
    op.drop_constraint(None, 'teacher_attendance_association', type_='foreignkey')
    op.drop_constraint(None, 'teacher_attendance_association', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_attendance_association_teacher_id_fkey'), 'teacher_attendance_association', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(op.f('teacher_attendance_association_attendance_id_fkey'), 'teacher_attendance_association', 'teacher_attendances', ['attendance_id'], ['id'])
    # ### end Alembic commands ###
