"""Add payment_month_start and end

Revision ID: fbd6bda667b4
Revises: f8c2d8de4020
Create Date: 2025-06-24 14:47:48.478315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd6bda667b4'
down_revision: Union[str, None] = 'f8c2d8de4020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'payment_month_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('transactions', 'payment_month_end',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'payment_month_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('transactions', 'payment_month_start',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
